---
driver                 :
    name               : localhost

provisioner:
    name               : ansible_push
    verbose            : "vvvv"
    ansible_config     : "test/ansible.cfg"
    idempotency_test   : False
    sudo               : True


platforms:
    - name                      : travis
      provisioner               :
        raw_arguments           : "-c local"

suites:
  - name            : ffmap-backend
    provisioner     :
        playbook    : "test/application/ffmap-backend_travis.yml"
        extra_vars  : { 'kitchen_connection': 'smart' }