---
# tasks file for ffmap-backend

- include_vars: "{{ ansible_os_family }}.yml"

- include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

- name: Install ffmap-backend dependencies
  apt: name={{item}} state=present
  with_items: "{{ffmap_backend_dependencies}}"

- name: Install python pip3
  apt: name=python3-pip state=present
  when: ffmap_backend_pip3_available

- name: Install python3 setup-tools
  when: not ffmap_backend_pip3_available
  apt: name=python3-setuptools state=present

- name: Install ffmap-backend python dependencies via pip
  when: ffmap_backend_pip3_available
  pip: name={{item}} executable="{{ffmap_backend_pip_executable}}"
  with_items: "{{ffmap_backend_python_dependencies}}"

- name: Install ffmap-backend python dependencies via easy_install
  when: not ffmap_backend_pip3_available
  easy_install: name={{item}} executable=easy_install3
  with_items: "{{ffmap_backend_python_dependencies}}"

- name: Create install directory for ffmap-backend
  file: dest={{ffmap_backend_install_dir}} state=directory

- name: Clone ffmap-backend sources
  git: repo={{ffmap_backend_repo_url}} version={{ffmap_backend_version}} dest={{ffmap_backend_install_dir}}

- name: Add ffmap-backend cron entry
  template: src=ffmap-backend.cron.j2 dest=/etc/cron.d/ffmap-backend
  notify: Restart cron